<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKFPEwfu\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKFPEwfu/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKFPEwfu.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKFPEwfu\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKFPEwfu\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'KFPEwfu',
    'container.build_id' => '9d389743',
    'container.build_time' => 1535410417,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKFPEwfu');
