<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIWo73fm\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIWo73fm/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIWo73fm.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIWo73fm\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIWo73fm\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'IWo73fm',
    'container.build_id' => '15689797',
    'container.build_time' => 1537562148,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIWo73fm');
